[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "supabase>=2.17.0",
]
